In [1]:
import numpy as np

In [2]:
arr = np.array([3,4,5])

In [3]:
arr

array([3, 4, 5])

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.full((8,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [8]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.eye(9)


array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [11]:
np.arange(0, 23 , 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [12]:
np.linspace(0 , 100 , 6)

array([  0.,  20.,  40.,  60.,  80., 100.])

In [26]:
arr = np.array([[1,2,3] , [4,5,6] , [6,7,8] , [9,10,11]])

In [15]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [11, 12, 13]])

In [17]:
arr.shape


(5, 3)

In [18]:
arr.size

15

In [21]:
arr.dtype

dtype('int64')

In [22]:
arr.ndim

2

In [28]:
arr.reshape((3,4))


array([[ 1,  2,  3,  4],
       [ 5,  6,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
flat = arr.flatten()  # Convert 2D → 1D

In [39]:
flat

array([ 1,  2,  3,  4,  5,  6,  6,  7,  8,  9, 10, 11])

In [42]:
flat[0]

np.int64(1)

In [43]:
flat[2]

np.int64(3)