In [1]:
import numpy as np


In [9]:
arr = np.array([[1,2,3] , [4,5,6] , [6,7,8] , [9,10,11]])

In [10]:
arr


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
flatt = arr.flatten()

In [12]:
flatt

array([ 1,  2,  3,  4,  5,  6,  6,  7,  8,  9, 10, 11])

In [13]:
arr[3:5]

array([[ 9, 10, 11]])

In [14]:
flatt[3:5]

array([4, 5])