In [2]:
import numpy as np

In [3]:
np.set_printoptions(legacy='1.25')

In [5]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [6]:
np.sum(arr)

45

In [7]:
arr[2 , 1]

8

In [8]:
arr[0: , :]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:

np.sum(arr , axis=0)

array([12, 15, 18])

In [10]:

np.sum(arr , axis = 1)

array([ 6, 15, 24])

In [11]:
aln = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

In [12]:
aln[0:2, 1:3]

array([[20, 30],
       [50, 60]])

In [13]:
np.sum(aln, axis=0)

array([120, 150, 180])

In [14]:
np.sum(aln, axis=1)

array([ 60, 150, 240])

In [4]:
arri = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

In [6]:
arri.shape

(2, 2, 3)

In [7]:
arri[1, 0, 2]

9

In [8]:
arre = np.array([10, 20, 30])

print(arre.dtype)

int64


In [9]:
arree = np.array([1.5, 2.5, 3.5])

print(arree.dtype)

float64


In [10]:
arro = np.array([1, 2, 3], dtype=np.float32)

print(arro.dtype)

float32


In [11]:
arr = np.array([1.9, 2.9, 3.9])

new_arr = arr.astype(np.int32)

print(new_arr)

[1 2 3]


In [13]:
arrp = np.array(
    ["apple", "banana", "cherry"],
    dtype="U10"
)

print(arrp)

['apple' 'banana' 'cherry']
